Repository cdklabs/cdk-appflow, pull requests merged in 2025-09, with the labels that each got.

#592 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve

#595 chore(deps): upgrade dev dependencies
  package.json
  yarn.lock
Labels: auto-approve, queued

#597 feat: Upgrading NodeJS AWS Lambda Runtime to nodejs22.x
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-cdklabs-projen-project-types-main.yml
  .github/workflows/upgrade-dev-deps-main.yml
  .github/workflows/upgrade-main.yml
  .mergify.yml
  .projen/deps.json
  .projen/tasks.json
  .projenrc.ts
  package.json
  src/core/flows/flow-time-updater/flow-time-updater-function.ts
  test/integ/ondemand-asana-to-s3.integ.snapshot/TestStack.assets.json
  test/integ/ondemand-asana-to-s3.integ.snapshot/TestStack.template.json
  test/integ/ondemand-googleanalytics4-to-s3.integ.snapshot/TestStack.assets.json
  test/integ/ondemand-googleanalytics4-to-s3.integ.snapshot/TestStack.template.json
  test/integ/ondemand-hubspot-to-s3.integ.snapshot/TestStack.assets.json
  test/integ/ondemand-hubspot-to-s3.integ.snapshot/TestStack.template.json
  test/integ/ondemand-jdbcsmalldatascale-to-amazonrdsforpostgresql.integ.snapshot/TestStack.assets.json
  test/integ/ondemand-jdbcsmalldatascale-to-amazonrdsforpostgresql.integ.snapshot/cdk.out
  test/integ/ondemand-jdbcsmalldatascale-to-amazonrdsforpostgresql.integ.snapshot/manifest.json
  test/integ/ondemand-jdbcsmalldatascale-to-s3.integ.snapshot/TestStack.assets.json
  test/integ/ondemand-jdbcsmalldatascale-to-s3.integ.snapshot/TestStack.template.json
  test/integ/ondemand-jdbcsmalldatascale-to-s3.integ.snapshot/cdk.out
  test/integ/ondemand-jdbcsmalldatascale-to-s3.integ.snapshot/manifest.json
  test/integ/ondemand-mailchimp-to-s3.integ.snapshot/TestStack.assets.json
  test/integ/ondemand-mailchimp-to-s3.integ.snapshot/TestStack.template.json
  test/integ/ondemand-microsoftdynamics365-to-s3.integ.snapshot/TestStack.assets.json
  test/integ/ondemand-microsoftdynamics365-to-s3.integ.snapshot/TestStack.template.json
  test/integ/ondemand-microsoftdynamics365-to-s3.integ.snapshot/cdk.out
  test/integ/ondemand-microsoftdynamics365-to-s3.integ.snapshot/manifest.json
  test/integ/ondemand-microsoftsharepointonline-to-s3.integ.snapshot/TestStack.assets.json
  test/integ/ondemand-microsoftsharepointonline-to-s3.integ.snapshot/TestStack.template.json
  test/integ/ondemand-s3-to-hubspot.integ.snapshot/TestStack.assets.json
  test/integ/ondemand-s3-to-hubspot.integ.snapshot/TestStack.template.json
  test/integ/ondemand-s3-to-s3.integ.snapshot/TestStack.assets.json
  test/integ/ondemand-s3-to-s3.integ.snapshot/TestStack.template.json
  test/integ/ondemand-s3-to-snowflake.integ.snapshot/TestStack.assets.json
  test/integ/ondemand-s3-to-snowflake.integ.snapshot/TestStack.template.json
  test/integ/ondemand-salesforce-to-redshift.integ.snapshot/TestStack.assets.json
  test/integ/ondemand-salesforce-to-redshift.integ.snapshot/TestStack.template.json
  test/integ/ondemand-salesforce-to-s3.integ.snapshot/TestStack.assets.json
  test/integ/ondemand-salesforce-to-s3.integ.snapshot/TestStack.template.json
  test/integ/ondemand-sapodata-to-s3.integ.snapshot/TestStack.assets.json
  test/integ/ondemand-sapodata-to-s3.integ.snapshot/TestStack.template.json
  test/integ/ondemand-slack-to-s3.integ.snapshot/TestStack.assets.json
  test/integ/ondemand-slack-to-s3.integ.snapshot/TestStack.template.json
  test/integ/onevent-salesforce-to-eventbridge.integ.snapshot/TestStack.assets.json
  test/integ/onevent-salesforce-to-eventbridge.integ.snapshot/TestStack.template.json
  test/integ/onschedule-s3-to-salesforce.integ.snapshot/TestStack.assets.json
  test/integ/onschedule-s3-to-salesforce.integ.snapshot/TestStack.template.json
  test/integ/onschedule-salesforce-marketing-cloud-to-s3.integ.snapshot/TestStack.assets.json
  test/integ/onschedule-salesforce-marketing-cloud-to-s3.integ.snapshot/TestStack.template.json
  yarn.lock
Labels: queued
